### PR TITLE
A few updates

### PR DESCRIPTION
**Pull request by k722003**
1) Removed unused import statements in all py files
2) Added newlines in the default config variable so as to make it more readable
3) Changed the converted list variable used to temporarily store converted images into a gen expr which uses less memory
4) Removed the pycache files
5) ~~Changed the __problem_char_rm to use regex instead of looping through the entire list of bad chars and using replace.~~ Decided to directly put the regex sub in places where this fn was called, since it was only called 2x

### CODE REVIEW

**Comment by k722003** [comment]
I have no idea why it says:
src/DownloadHandler.py
src/PDFHandler.py
src/PathHandler.py 
cannot be resolved automatically

**Comment by TacoAnime69** [comment]
Ah sorry, I've been making some changes. Let me finish up some stuff, then you can pull my changes to your fork, and hopefully avoid conflict.

**Comment by TacoAnime69** [comment]
Ok, I didn't realize my IDE did some weird auto formatting with the config part. I think it's fine now, but feel free to change that back. I updated master and removed some weird files that got added. It's working fine for me, but do test on Windows to make sure nothing is broken there. I tested on Linux and Mac. 

You'll probably want to pull my changes.
Thanks!

**Comment by TacoAnime69** [comment]
Going to close this pull request, thanks for the changes.

**Comment by k722003** [comment]
no probs

**Pull request closed without merging**
