### PR TITLE
Update __main__.py

### PR DESCRIPTION
**Pull request by k722003**
1) Added config file that would allow the user to specify an output folder, naming scheme of the file and batch downloading. Will be created automatically if doesn't exist in cwd
2) Removed redundant newlines, white spaces, return statements
3) Users can now provide URLs or Ids. Ids must be separated by any delimiter whereas URLs need no delimiter. This is because each consecutive block of numbers is considered an Id

### CODE REVIEW

**Comment by TacoAnime69** [comment]
Sorry I'm late to this. Thank you for your contribution! I'll test this out ASAP.

**Comment by TacoAnime69** [comment]
Looks good. I kinda wish the default settings were a bit different. But I like that it's now easy to change with the config.

**Comment by k722003** [comment]
The README.md should prob be updated.

**Comment by TacoAnime69** [comment]
oh yeah, probably should. I'll take care of that later today.

**Pull request merged**
