### PR TITLE
Updated __main__.py and readme

### PR DESCRIPTION
**Pull request by k722003**
### \_\_main\_\_.py changes:
  1) Added threads(see point 3)
  2) Added support for cbr,cbz,cbt(see point 3)
  3) Added additional info and 2 new parameters to the config file:
      a) threads: Used to set how many threads are to be used for downloading, i.e how many pages are to be downloaded at once
      b) type: Set the file extension that the doujin is to be saved as. Currently supports pdf(default), cbr, cbt, cbz. Note that the compression used for all 3 CBx formats is zip(it just works)
  4) Modified the import statements a bit.
  5) Changed the downloading progress section in the script to a nice tabular form
  6) Some minor string and formatting changes

### README.MD changes:
- Updated the readme file

### Note:
- For automatically putting downloaded PDF into a subfolder named after its parody, author, or language, the tags etc need to be extracted similar to how you extracted the title name, page count etc. But I don't know how to do that hence I left it

### CODE REVIEW

**Comment by k722003** [comment]
Oh, and also made it so that if the device has LongPathsEnabled in the registry, then the file name limit will be ignored

**Comment by TacoAnime69** [comment]
Wow amazing! Shame on me for forgetting to update the readme file from last time. I'll test your changes this after noon to confirm everything is good. 
I didn't even know there's a LongPathsEnabled registry value. That's interesting. 

Regarding the note, I'll add a tag extraction method and see if I can get that implemented. Otherwise it can wait for another time.

**Comment by TacoAnime69** [comment]
Okay, looks good! I really like the new download progress text. The only thing that needs to be changed is to update the .gitignore to include the config file. Probably should have done that for the last merge. I'll do that immediately after merging.

**Comment by TacoAnime69** [comment]
Oh crap. I just realize the WinReg module is being used. It's really important to me that this stays cross compatible with Linux and MacOS. So I'll be making changes.

**Comment by k722003** [comment]
```
    def valid(self):
        #This reg key if set to 1 removes the char limit for path
        long_paths_enabled = sys.platform == 'win32' and winreg.QueryValueEx( winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, 
            r'SYSTEM\CurrentControlSet\Control\FileSystem'), 'LongPathsEnabled')[0] == 1
        return long_paths_enabled or (len(self._final_path) < 200)```
       
just add the ` sys.platform == 'win32' and` after the ` long_paths_enabled =` to prevent winreg from being used on non windows OS

**Comment by TacoAnime69** [comment]
Oh I just saw this. I figured it out already. But thanks! I'll change it to what you have cause that was cleaner.

**Comment by TacoAnime69** [comment]
Made the change.

**Pull request merged**
